### ISSUE TITLE
Issue with something, i don't remember

### ISSUE THREAD

**Issue by Zempat** [Ordinastie/MalisisSwitches#13]
Here's the crash report: WARNING: coremods are present:
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  weaponlib (mw-1.11.7.7_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 7/11/19 9:08 PM
Description: Rendering item

java.lang.IllegalStateException: Not building!
	at net.minecraft.client.renderer.BufferBuilder.func_178977_d(BufferBuilder.java:537)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
	at com.vicmatskiv.weaponlib.compatibility.CompatibleWeaponRenderer.func_188616_a(CompatibleWeaponRenderer.java:137)
	at net.minecraftforge.client.ForgeHooksClient.renderLitItem(ForgeHooksClient.java:653)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:118)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:149)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:308)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:347)
	at net.minecraft.client.renderer.RenderItem.func_180450_b(RenderItem.java:336)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:922)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:758)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.BufferBuilder.func_178977_d(BufferBuilder.java:537)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
	at com.vicmatskiv.weaponlib.compatibility.CompatibleWeaponRenderer.func_188616_a(CompatibleWeaponRenderer.java:137)
	at net.minecraftforge.client.ForgeHooksClient.renderLitItem(ForgeHooksClient.java:653)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:118)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:149)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:308)

-- Item being rendered --
Details:
	Item Type: com.vicmatskiv.weaponlib.Weapon@12b8b7c8
	Registry Name: mw:m16a4
	Item Aux: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:347)
	at net.minecraft.client.renderer.RenderItem.func_180450_b(RenderItem.java:336)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:922)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:758)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (303, 19). Absolute: (1820, 1323)
	Screen size: Scaled: (427, 240). Absolute: (2560, 1440). Scale factor of 6

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Zempat'/12, l='MpServer', x=965.50, y=12.51, z=-596.50]]
	Chunk stats: MultiplayerChunkCache: 529, 529
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (965,4,-598), Chunk: (at 5,0,10 in 60,-38; contains blocks 960,0,-608 to 975,255,-593), Region: (1,-2; contains chunks 32,-64 to 63,-33, blocks 512,0,-1024 to 1023,255,-513)
	Level time: 321 game time, 321 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 2 total; [EntityLatchedRenderer['unknown'/5969, l='MpServer', x=8.50, y=65.00, z=8.50], EntityPlayerSP['Zempat'/12, l='MpServer', x=965.50, y=12.51, z=-596.50]]
	Retry entities: 1 total; [EntityLatchedRenderer['unknown'/5969, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 520885120 bytes (496 MB) / 1744830464 bytes (1664 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID              | Version               | Source                                            | Signature                                |
	|:------ |:--------------- |:--------------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft       | 1.12.2                | minecraft.jar                                     | None                                     |
	| LCHIJA | mcp             | 9.42                  | minecraft.jar                                     | None                                     |
	| LCHIJA | FML             | 8.0.99.99             | forge-1.12.2-14.23.5.2838.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge           | 14.23.5.2838          | forge-1.12.2-14.23.5.2838.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | cfm             | 6.3.0                 | furniture-6.3.0-1.12.2.jar                        | None                                     |
	| LCHIJA | ichunutil       | 7.2.1                 | iChunUtil-1.12.2-7.2.1.jar                        | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | malisiscore     | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                      | None                                     |
	| LCHIJA | malisisdoors    | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                     | None                                     |
	| LCHIJA | malisisswitches | 1.12.2-5.1.0          | malisisswitches-1.12.2-5.1.0.jar                  | None                                     |
	| LCHIJA | mobamputation   | 7.0.0                 | MobAmputation-1.12.2-7.0.0.jar                    | None                                     |
	| LCHIJA | mw              | 1.11.7.7              | mw-1.11.7.7_mc1.12.2.jar                          | None                                     |
	| LCHIJA | sync            | 7.1.0                 | Sync-1.12.2-7.1.0.jar                             | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | worldedit       | 6.1.10-SNAPSHOT       | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |

	Loaded coremods (and transformers): 
MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
weaponlib (mw-1.11.7.7_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 419.35' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2838
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 419.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz

**Comment by Zempat** [comment]
Got it, it was Modern Warfare.
